name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: install Twilio plugin & serverless deploy
      uses: serverless/github-action@master
      with:
        args: -c "serverless plugin install -n @twilio-labs/serverless-twilio-runtime && serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
        entrypoint: /bin/sh
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        MY_PHONE_NUMBER: ${{ secrets.MY_PHONE_NUMBER }}